{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "3.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.7.jar",
          "url": "spring-boot-starter-test-3.5.7.jar",
          "size": 4790,
          "sha512": "aa014bcfb5f20ac08ad23c458eee552ddee5463ac71cf89e29833cb592186505283515f66803931b8f94e8eaf69e6e91bdb96915f12b18985886425255ae5fad",
          "sha256": "57aab82b08dd7dc6bd32de827c8c42a67558a83023701c3084e9ed5763069b6c",
          "sha1": "a460fe60ea4c396c782f1c95743525a64ab1c0b6",
          "md5": "ed6405ff2888f1c6fab68a30263de484"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "net.minidev",
          "module": "json-smart",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.27.6"
          }
        },
        {
          "group": "org.awaitility",
          "module": "awaitility",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.12.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "5.17.0"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.12"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.10.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.7.jar",
          "url": "spring-boot-starter-test-3.5.7.jar",
          "size": 4790,
          "sha512": "aa014bcfb5f20ac08ad23c458eee552ddee5463ac71cf89e29833cb592186505283515f66803931b8f94e8eaf69e6e91bdb96915f12b18985886425255ae5fad",
          "sha256": "57aab82b08dd7dc6bd32de827c8c42a67558a83023701c3084e9ed5763069b6c",
          "sha1": "a460fe60ea4c396c782f1c95743525a64ab1c0b6",
          "md5": "ed6405ff2888f1c6fab68a30263de484"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.7-javadoc.jar",
          "url": "spring-boot-starter-test-3.5.7-javadoc.jar",
          "size": 4790,
          "sha512": "e1ff7181b20c8fca5eb78876721502ce11020d41ae9ef5e548f96a3358096a1b225a6206f58fe095f52002ba9b95cb7f52a50558f86840e26630425806a6d48d",
          "sha256": "b90980cd661546683b40427a6aed3842cb81eed26ae5dac5e1caf0f9acb53714",
          "sha1": "d469257f24cb0b8e9ba5e91dbeb2460c4453f9c3",
          "md5": "8e82d0cccd0ab9297a49915bf67d0ad6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-3.5.7-sources.jar",
          "url": "spring-boot-starter-test-3.5.7-sources.jar",
          "size": 4790,
          "sha512": "e1ff7181b20c8fca5eb78876721502ce11020d41ae9ef5e548f96a3358096a1b225a6206f58fe095f52002ba9b95cb7f52a50558f86840e26630425806a6d48d",
          "sha256": "b90980cd661546683b40427a6aed3842cb81eed26ae5dac5e1caf0f9acb53714",
          "sha1": "d469257f24cb0b8e9ba5e91dbeb2460c4453f9c3",
          "md5": "8e82d0cccd0ab9297a49915bf67d0ad6"
        }
      ]
    }
  ]
}
